# Generated by Django 5.0.1 on 2024-03-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_askqa'),
    ]

    operations = [
        migrations.AddField(
            model_name='askqa',
            name='detail_asnwer',
            field=models.TextField(blank=True, null=True, verbose_name='คำตอบ'),
        ),
        migrations.AlterField(
            model_name='askqa',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ชื่อผู้ติดต่อ'),
        ),
    ]
